### ISSUE TITLE
Puppeteer 10.4 features

### ISSUE THREAD

**Issue by YusukeIwaki** [YusukeIwaki/puppeteer-ruby#143]
https://github.com/puppeteer/puppeteer/releases/tag/v10.4.0

**Comment by YusukeIwaki** [comment]
* [] add webp to screenshot options (#7565) (43a9268)
* [] add ability to specify offsets for JSHandle.click (#7573) (2b5c001)
* [] add durableStorage to allowed permissions (#5295) (eda5171)
* [] add id option to addScriptTag (#5477) (300be5d)
* [] add more Android models to DeviceDescriptors (#7210) (b5020dc), closes /github.com/aerokube/moon-deploy/blob/master/moon-local.yaml#L199
* [] add proxy and bypass list parameters to createIncognitoBrowserContext (#7516) (8e45a1c), closes #678
* [] add threshold to Page.isIntersectingViewport (#6497) (54c4318)
* [] add unit test support for bisect (#7553) (a0b1f6b)
* [] add User-Agent with Puppeteer version to WebSocket request (#5614) (6a2bf0a)
* [] extend husky checks (#7574) (7316086)
* [] api: implement Page.waitForNetworkIdle() (#5140) (3c6029c)
* [] coverage: option for raw V8 script coverage (#6454) (cb4470a)
* [] support timeout for page.pdf() call (#7508) (f90af66)
* ~~typescript: allow using puppeteer without dom lib (#6998) (723052d), closes #6989~~
* ~~docs: deploy includes website documentation (#7469) (6fde41c)~~
* ~~docs: names in version 9.1.1 (#7517) (44b22bb)~~
* [] frame: fix Frame.waitFor's XPath pattern detection (#5184) (caa2b73)
* ~~install: respect environment proxy config when downloading Firef… (#6577) (9399c97), closes #6573~~
* ~~added names in V9.1.1 (#7547) (d132b8b)~~
* [] test: tweak waitForNetworkIdle delay in test between downloads (#7564) (a21b737)
* ~~types: allow evaluate functions to take a readonly array as an argument (#7072) (491614c)~~
* ~~update firefox prefs documentation link (#7539) (2aec355)~~
* [] use non-deprecated tracing categories api (#7413) (040a0e5)

**Comment by YusukeIwaki** [comment]
`Page.waitForNetworkIdle()` is not implemented just now.
It will be implemented if needed.

**Comment by sebyx07** [comment]
> * add proxy and bypass list parameters to createIncognitoBrowserContext
> * api: implement Page.waitForNetworkIdle()
> 
> These features are not implemented just now. They will be implemented if needed.

proxy would be great
